-- 0024: hot-path indexes + new unique keys. Generated by scripts/dev/gen-reconcile.mjs; guarded and
-- re-runnable. Duplicate rows are collapsed BEFORE each new unique key so the ALTER cannot fail.

-- dedupe before the new unique keys (keep the newest row)
DELETE lb FROM leave_balances lb JOIN leave_balances lb2 ON lb.traineeCode = lb2.traineeCode AND lb.year = lb2.year AND lb.id < lb2.id;
DELETE bc FROM batch_candidates bc JOIN batch_candidates bc2 ON bc.batchId = bc2.batchId AND bc.candidateId = bc2.candidateId AND bc.id < bc2.id;
DELETE it FROM integrations_tokens it JOIN integrations_tokens it2 ON it.provider = it2.provider AND ((it.userId IS NULL AND it2.userId IS NULL) OR it.userId = it2.userId) AND it.id < it2.id;

SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_advances' AND INDEX_NAME = 'idx_adv_trainee_created') = 0,
  'CREATE INDEX `idx_adv_trainee_created` ON `agent_advances` (`traineeCode`,`createdAt`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_advances' AND INDEX_NAME = 'idx_adv_status_cycle') = 0,
  'CREATE INDEX `idx_adv_status_cycle` ON `agent_advances` (`status`,`deductCycle`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_advances' AND INDEX_NAME = 'idx_adv_created') = 0,
  'CREATE INDEX `idx_adv_created` ON `agent_advances` (`createdAt`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_aux_logs' AND INDEX_NAME = 'idx_aux_trainee_start') = 0,
  'CREATE INDEX `idx_aux_trainee_start` ON `agent_aux_logs` (`traineeCode`,`startTime`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_aux_logs' AND INDEX_NAME = 'idx_aux_trainee_end') = 0,
  'CREATE INDEX `idx_aux_trainee_end` ON `agent_aux_logs` (`traineeCode`,`endTime`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_documents' AND INDEX_NAME = 'idx_adoc_trainee') = 0,
  'CREATE INDEX `idx_adoc_trainee` ON `agent_documents` (`traineeCode`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_notifications' AND INDEX_NAME = 'idx_notif_cand_read') = 0,
  'CREATE INDEX `idx_notif_cand_read` ON `agent_notifications` (`candidateId`,`isRead`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_payment_methods' AND INDEX_NAME = 'idx_apm_trainee') = 0,
  'CREATE INDEX `idx_apm_trainee` ON `agent_payment_methods` (`traineeCode`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_presence' AND INDEX_NAME = 'idx_presence_lastseen') = 0,
  'CREATE INDEX `idx_presence_lastseen` ON `agent_presence` (`lastSeen`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_requests' AND INDEX_NAME = 'idx_req_trainee_created') = 0,
  'CREATE INDEX `idx_req_trainee_created` ON `agent_requests` (`traineeCode`,`createdAt`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_requests' AND INDEX_NAME = 'idx_req_status_created') = 0,
  'CREATE INDEX `idx_req_status_created` ON `agent_requests` (`status`,`createdAt`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_requests' AND INDEX_NAME = 'idx_req_slack_ts') = 0,
  'CREATE INDEX `idx_req_slack_ts` ON `agent_requests` (`slackMessageTs`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_shifts' AND INDEX_NAME = 'idx_agent_shifts_trainee_date') = 0,
  'CREATE INDEX `idx_agent_shifts_trainee_date` ON `agent_shifts` (`traineeCode`,`date`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_shifts' AND INDEX_NAME = 'idx_shift_open') = 0,
  'CREATE INDEX `idx_shift_open` ON `agent_shifts` (`clockOut`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_shifts' AND INDEX_NAME = 'idx_shift_trainee_clockin') = 0,
  'CREATE INDEX `idx_shift_trainee_clockin` ON `agent_shifts` (`traineeCode`,`clockIn`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'attendance_exceptions' AND INDEX_NAME = 'idx_attx_trainee_date_type') = 0,
  'CREATE INDEX `idx_attx_trainee_date_type` ON `attendance_exceptions` (`traineeCode`,`date`,`exceptionType`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'audit_log' AND INDEX_NAME = 'idx_audit_created') = 0,
  'CREATE INDEX `idx_audit_created` ON `audit_log` (`createdAt`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'audit_log' AND INDEX_NAME = 'idx_audit_action_created') = 0,
  'CREATE INDEX `idx_audit_action_created` ON `audit_log` (`action`,`createdAt`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'batch_candidates' AND INDEX_NAME = 'idx_bc_batch') = 0,
  'CREATE INDEX `idx_bc_batch` ON `batch_candidates` (`batchId`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'batch_candidates' AND INDEX_NAME = 'idx_bc_candidate') = 0,
  'CREATE INDEX `idx_bc_candidate` ON `batch_candidates` (`candidateId`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'candidates' AND INDEX_NAME = 'idx_cand_phone') = 0,
  'CREATE INDEX `idx_cand_phone` ON `candidates` (`phone`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'candidates' AND INDEX_NAME = 'idx_cand_status') = 0,
  'CREATE INDEX `idx_cand_status` ON `candidates` (`status`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cycle_deductions' AND INDEX_NAME = 'idx_cycle_deductions_cycle') = 0,
  'CREATE INDEX `idx_cycle_deductions_cycle` ON `cycle_deductions` (`cycleKey`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cycle_ot' AND INDEX_NAME = 'idx_cycle_ot_cycle') = 0,
  'CREATE INDEX `idx_cycle_ot_cycle` ON `cycle_ot` (`cycleKey`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cycle_stats' AND INDEX_NAME = 'idx_cycle_stats_cycle') = 0,
  'CREATE INDEX `idx_cycle_stats_cycle` ON `cycle_stats` (`cycleKey`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'leave_requests' AND INDEX_NAME = 'idx_leave_trainee_status') = 0,
  'CREATE INDEX `idx_leave_trainee_status` ON `leave_requests` (`traineeCode`,`status`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'leave_requests' AND INDEX_NAME = 'idx_leave_agent_request') = 0,
  'CREATE INDEX `idx_leave_agent_request` ON `leave_requests` (`agentRequestId`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'login_attempts' AND INDEX_NAME = 'idx_login_ident_type_at') = 0,
  'CREATE INDEX `idx_login_ident_type_at` ON `login_attempts` (`identifier`,`attemptType`,`failedAt`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'payroll_adjustments' AND INDEX_NAME = 'idx_padj_crdts_month') = 0,
  'CREATE INDEX `idx_padj_crdts_month` ON `payroll_adjustments` (`crdts`,`month`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'payroll_records' AND INDEX_NAME = 'idx_payroll_crdts_month') = 0,
  'CREATE INDEX `idx_payroll_crdts_month` ON `payroll_records` (`crdts`,`month`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'session_logs' AND INDEX_NAME = 'idx_session_user') = 0,
  'CREATE INDEX `idx_session_user` ON `session_logs` (`userId`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'workforce_agents' AND INDEX_NAME = 'idx_wa_candidate') = 0,
  'CREATE INDEX `idx_wa_candidate` ON `workforce_agents` (`candidateId`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'workforce_agents' AND INDEX_NAME = 'idx_wa_campaign_status') = 0,
  'CREATE INDEX `idx_wa_campaign_status` ON `workforce_agents` (`campaignId`,`agentStatus`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'workforce_agents' AND INDEX_NAME = 'idx_wa_openid') = 0,
  'CREATE INDEX `idx_wa_openid` ON `workforce_agents` (`openId`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;

-- unique keys that live inline in CREATE TABLE (added here for tables that pre-exist)
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'adherence_log' AND INDEX_NAME = 'uq_adherence_agent_date_type') = 0,
  'ALTER TABLE `adherence_log` ADD UNIQUE INDEX `uq_adherence_agent_date_type` (`agentCode`,`date`,`type`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'admin_accounts' AND INDEX_NAME = 'admin_accounts_email_unique') = 0,
  'ALTER TABLE `admin_accounts` ADD UNIQUE INDEX `admin_accounts_email_unique` (`email`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'admin_invites' AND INDEX_NAME = 'admin_invites_token_unique') = 0,
  'ALTER TABLE `admin_invites` ADD UNIQUE INDEX `admin_invites_token_unique` (`token`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_contracts' AND INDEX_NAME = 'agent_contracts_traineeCode_unique') = 0,
  'ALTER TABLE `agent_contracts` ADD UNIQUE INDEX `agent_contracts_traineeCode_unique` (`traineeCode`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_credentials' AND INDEX_NAME = 'agent_credentials_candidateId_unique') = 0,
  'ALTER TABLE `agent_credentials` ADD UNIQUE INDEX `agent_credentials_candidateId_unique` (`candidateId`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_credentials' AND INDEX_NAME = 'agent_credentials_traineeCode_unique') = 0,
  'ALTER TABLE `agent_credentials` ADD UNIQUE INDEX `agent_credentials_traineeCode_unique` (`traineeCode`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'agent_violations' AND INDEX_NAME = 'uq_violation_agent_date_type') = 0,
  'ALTER TABLE `agent_violations` ADD UNIQUE INDEX `uq_violation_agent_date_type` (`agentCode`,`date`,`type`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'api_keys' AND INDEX_NAME = 'api_keys_key_hash_unique') = 0,
  'ALTER TABLE `api_keys` ADD UNIQUE INDEX `api_keys_key_hash_unique` (`key_hash`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'batch_candidates' AND INDEX_NAME = 'uq_bc_batch_candidate') = 0,
  'ALTER TABLE `batch_candidates` ADD UNIQUE INDEX `uq_bc_batch_candidate` (`batchId`,`candidateId`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'break_schedules' AND INDEX_NAME = 'break_schedules_agent_date_idx_unique') = 0,
  'ALTER TABLE `break_schedules` ADD UNIQUE INDEX `break_schedules_agent_date_idx_unique` (`agentCode`,`date`,`breakIndex`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'client_positions' AND INDEX_NAME = 'uq_client_position') = 0,
  'ALTER TABLE `client_positions` ADD UNIQUE INDEX `uq_client_position` (`clientId`,`name`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'commission_leaderboard' AND INDEX_NAME = 'uq_commission_leaderboard_cycle_crdts') = 0,
  'ALTER TABLE `commission_leaderboard` ADD UNIQUE INDEX `uq_commission_leaderboard_cycle_crdts` (`cycleKey`,`crdts`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'commissions' AND INDEX_NAME = 'uq_commissions_crdts_cycle') = 0,
  'ALTER TABLE `commissions` ADD UNIQUE INDEX `uq_commissions_crdts_cycle` (`crdts`,`paymentCycle`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cycle_deductions' AND INDEX_NAME = 'uq_cycle_deductions_crdts_date_type') = 0,
  'ALTER TABLE `cycle_deductions` ADD UNIQUE INDEX `uq_cycle_deductions_crdts_date_type` (`crdts`,`date`,`violationType`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cycle_ot' AND INDEX_NAME = 'uq_cycle_ot_crdts_date_type') = 0,
  'ALTER TABLE `cycle_ot` ADD UNIQUE INDEX `uq_cycle_ot_crdts_date_type` (`crdts`,`date`,`otType`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cycle_stats' AND INDEX_NAME = 'uq_cycle_stats_crdts_date') = 0,
  'ALTER TABLE `cycle_stats` ADD UNIQUE INDEX `uq_cycle_stats_crdts_date` (`crdts`,`date`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'exit_process' AND INDEX_NAME = 'exit_process_traineeCode_unique') = 0,
  'ALTER TABLE `exit_process` ADD UNIQUE INDEX `exit_process_traineeCode_unique` (`traineeCode`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'integrations_tokens' AND INDEX_NAME = 'uq_integration_provider_user') = 0,
  'ALTER TABLE `integrations_tokens` ADD UNIQUE INDEX `uq_integration_provider_user` (`provider`,`userId`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'leave_balances' AND INDEX_NAME = 'uq_leave_balance') = 0,
  'ALTER TABLE `leave_balances` ADD UNIQUE INDEX `uq_leave_balance` (`traineeCode`,`year`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'payroll_records' AND INDEX_NAME = 'uq_payroll_agentcode_month') = 0,
  'ALTER TABLE `payroll_records` ADD UNIQUE INDEX `uq_payroll_agentcode_month` (`agentCode`,`month`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'quality_log' AND INDEX_NAME = 'uq_quality_agent_date_type') = 0,
  'ALTER TABLE `quality_log` ADD UNIQUE INDEX `uq_quality_agent_date_type` (`agentCode`,`date`,`type`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'team_leaders' AND INDEX_NAME = 'team_leaders_name_unique') = 0,
  'ALTER TABLE `team_leaders` ADD UNIQUE INDEX `team_leaders_name_unique` (`name`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'users' AND INDEX_NAME = 'users_openId_unique') = 0,
  'ALTER TABLE `users` ADD UNIQUE INDEX `users_openId_unique` (`openId`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
SET @q = IF((SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'workforce_agents' AND INDEX_NAME = 'workforce_agents_traineeCode_unique') = 0,
  'ALTER TABLE `workforce_agents` ADD UNIQUE INDEX `workforce_agents_traineeCode_unique` (`traineeCode`)', 'SELECT 1');
PREPARE s FROM @q;
EXECUTE s;
DEALLOCATE PREPARE s;
